# Change these first
owner: megasin2 # Your GitHub organization or username, where this repository lives
repo: statustracker # The name of this repository

sites:
  - name: Primary Server-1hd-buzz
    url: https://1hd.buzz
  - name: testing environment -doo
    url: https://doo.1hd.buzz
  - name: Subdomains 2 eu.org
    url: https://bollymovie2.eu.org
  - name: Subdomains 3 eu.org
    url: https://bollyhdmovie.eu.org
  - name: FastHD Server -VRC
    url: https://fast.1hd.buzz
  - name: Braflix Server -VRC
    url: https://braflix.1hd.buzz
  - name: StreamHD Server -VRC
    url: https://stream.1hd.buzz
  - name: Watch Server -VRC
    url: https://watch.1hd.buzz
  - name: Play Server -VRC
    url: https://play.1hd.buzz
  - name: Status Server -VRC
    url: https://status.1hd.buzz
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.1hd.buzz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 1hd Status Page
  introTitle: "**1HD.buzz** Status Updates."
  introMessage: This is a  status page which uses **real-time** data from our Servers. including doo,1hdmain,braflix,fasthd, quick stream server
  navbar:
    - title: Status
      href: /
   

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
